#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_

#include "../../../LIB/std_types.h"

typedef enum{
    TIMER1_NORMAL,
    TIMER1_CTC_OCR1A,
    TIMER1_FAST_PWM_ICR1,
    TIMER1_PHASE_CORRECT_ICR1
}TIMER1_MODE_SELECT;

typedef enum{
    OC1_DISCONNECTED,
    TOGGLE_OC1,
    CLEAR_OC1,
    SET_OC1
}TIMER1_CTC_MODE_SELECT;

typedef enum{
    T1_NON_INVERTING,
    T1_INVERTING
}TIMER1_PWM_MODE_SELECT;

typedef enum{
    T1_NO_CLOCK,
	T1_NO_PRESCALER,
	T1_PRESCALER_8,
	T1_PRESCALER_64,
	T1_PRESCALER_256,
	T1_PRESCALER_1024
}TIMER1_CLOCK_SELECT;

#endif /* TIMER1_CONFIG_H_ */
