#ifndef MCAL_TIMERS_DRIVER_TIMER_CONFIG_H_
#define MCAL_TIMERS_DRIVER_TIMER_CONFIG_H_

typedef enum{
	NORMAL, PWM_PHASE_CORRECT, CTC, FAST_PWM
}WAVE_FORM_GENERATION_MODE_SELECT;

typedef enum{
	FAST_PWM_NORMAL, NON_INVERTING_MODE, INVERTING_MODE
}FAST_PWM_MODE_SELECT;

typedef enum{
	T0_NO_CLOCK,
	T0_NO_PRESCALER,
	T0_PRESCALER_8,
	T0_PRESCALER_64,
	T0_PRESCALER_256,
	T0_PRESCALER_1024
}TIMER0_CLOCK_SELECT;

#endif // MCAL_TIMERS_DRIVER_TIMER_CONFIG_H_
